from django import forms
from django.forms import HiddenInput


class createChapter(forms.Form):
    origin=HiddenInput()
    date_of_origin=HiddenInput()
    progenitor=HiddenInput()
    purity_shown=HiddenInput()
    demeanour=HiddenInput()
    deficiency=HiddenInput()
    flaw=HiddenInput()
    characteristic_modifier=HiddenInput()
    figure_of_legend=HiddenInput()
    deed_of_legend=HiddenInput()
    home_world=HiddenInput()
    chapter_organisation=HiddenInput()
    combat_doctrine=HiddenInput()
    solo_abilities=HiddenInput()
    squad_mode_abilities=HiddenInput()
    speciality_restrictions=HiddenInput()
    special_equipment=HiddenInput()
    chapter_beliefs=HiddenInput()
    current_status=HiddenInput()
    chapter_friends=HiddenInput()
    chapter_enemies=HiddenInput()
    chapter_advance=HiddenInput()    

class keepChapter(forms.Form):

    origin=HiddenInput()
    date_of_origin=HiddenInput()
    progenitor=HiddenInput()
    purity_shown=HiddenInput()
    demeanour=HiddenInput()
    deficiency=HiddenInput()
    flaw=HiddenInput()
    characteristic_modifier=HiddenInput()
    figure_of_legend=HiddenInput()
    deed_of_legend=HiddenInput()
    home_world=HiddenInput()
    chapter_organisation=HiddenInput()
    combat_doctrine=HiddenInput()
    solo_abilities=HiddenInput()
    squad_mode_abilities=HiddenInput()
    speciality_restrictions=HiddenInput()
    special_equipment=HiddenInput()
    chapter_beliefs=HiddenInput()
    current_status=HiddenInput()
    chapter_friends=HiddenInput()
    chapter_enemies=HiddenInput()
    chapter_advance=HiddenInput()
